accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import LogoutView

app_name = 'accounts'
urlpatterns = [

    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),
    url(r'^user_logout/$', LogoutView.as_view(), name = 'user_logout'),
    path('profile/<int:pk>/', views.my_profile, name= 'my_profile'),
    path('profile/delete_all_my_photos', views.delete_all_my_photos, name= 'delete_all_my_photos'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

travel/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from travel.views import CreatePhotoView, UpdatePhotoView, DeletePhotoView

app_name = 'travel'
urlpatterns = [
    url(r'^create/$', CreatePhotoView.as_view(), name = 'create'),
    url(r'^photos/$', views.all_photosListView.as_view(), name = 'all_photos'),
    path('photos/details/<int:pk>/',views.photo_details, name='photo_details'),
    path('edit/<int:pk>/', UpdatePhotoView.as_view(), name = 'edit_photo'),
    path('delete/<int:pk>/', DeletePhotoView.as_view(), name = 'delete_photo'),
    path('photos/like/<int:pk>/', views.like, name = 'like'),
    path('photos/edit_comment/<int:pk>/',views.edit_comment, name='edit_comment'),
    path('photos/delete_comment/<int:pk>/',views.delete_comment, name='delete_comment'),
    path('photos/details/<int:pk>/photos_of_user/',views.all_photos_of_user, name='photos_of_user'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelover/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('travel.urls')),
    path('', include('accounts.urls')),

]

travel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.http import request

from accounts.models import UserProfileInfo



class Photo(models.Model):
    user = models.ForeignKey(UserProfileInfo, default=1, on_delete=models.CASCADE)
    city = models.CharField(max_length=25)
    country = models.CharField(max_length=25)
    title = models.CharField(max_length=25)
    description = models.TextField()
    image_url = models.ImageField(upload_to='images')

    def __str__(self):
        return f"{self.title}: from {self.city}, {self.country}"


class Like(models.Model):
    photo = models.ForeignKey(to=Photo, default='', on_delete=models.CASCADE)
    user = models.ForeignKey(to=UserProfileInfo, default=1, on_delete=models.CASCADE)
    likes_count = ''

    def __str__(self):
        return f"{self.photo}"


class Comment(models.Model):
    photo = models.ForeignKey(to=Photo, default='', on_delete=models.CASCADE)
    user = models.ForeignKey(to=UserProfileInfo, default=1, on_delete=models.CASCADE)
    comment = models.TextField(max_length=256)

    def __str__(self):
        return f"{self.comment}"

travel/forms.py
from django import forms
from travel.models import Photo, Comment
from django.contrib.auth.models import User


class CreatePhotoForm(forms.ModelForm):
    city = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    country = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    title = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
    ))
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control rounded-2'
    }))

    image_url = forms.FileInput(
        attrs={
            'class': 'custom-file-input'
        }
    )

    class Meta:
        model = Photo
        fields = ['city', 'country', 'title', 'description', 'image_url']


class DeletePhotoForm(CreatePhotoForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['disabled'] = True
            field.widget.attrs['readonly'] = True


class CommentPhotoForm(forms.ModelForm):
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control rounded-2'
    }))

    class Meta:
        model = Comment
        fields = ['comment', ]


class DeleteComment(forms.ModelForm):
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control rounded-2'
    }))

    class Meta:
        model = Comment
        fields = '__all__'


class EditComment(forms.ModelForm):
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'form-control rounded-2'
    }))

    class Meta:
        model = Comment
        fields = ['comment', ]

travel/views.py
from django.forms import forms
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import mixins as auth_mixins
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from accounts.models import UserProfileInfo
from . import forms, models

# Create your views here.
from .forms import CommentPhotoForm, CreatePhotoForm, DeletePhotoForm, DeleteComment, EditComment
from .models import Photo, Comment, Like


#def all_photos(request):
#    current_user = request.user

#    photos_list = Photo.objects.order_by('title')

#    photos_dict = {'photos': photos_list,
#                  'profile': current_user,
#                   }
#    return render(request, 'travel/photos_list.html', context=photos_dict)



class all_photosListView(ListView):

    model = models.Photo
    template_name = 'travel/photos_list.html'

    def get_context_data(self, **kwargs):
        photos_list = Photo.objects.order_by('title')

        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        context['photos'] = photos_list
        return context


def photo_details(request, pk):
    current_user = request.user

    photos_list = Photo.objects.get(pk=pk)
    photos_list.see_edit_and_delete_button = photos_list.user.user_id == request.user.id

    comment_list = Comment.objects.all()
    for el in comment_list:
        el.see_buttons = el.user.user_id == request.user.id
        if el.see_buttons:
            pass

    already_liked = True if len(Like.objects.filter(photo=photos_list)) > 0 else False

    if request.method == "GET":

        photos_dict = {'photos_list': photos_list,
                       'form': CommentPhotoForm(),
                       'comment_list': comment_list,
                       'already_liked': already_liked,
                       'profile': current_user,
                       }
        return render(request, 'travel/photo_details.html', context=photos_dict)
    else:
        form = CommentPhotoForm(request.POST)
        if form.is_valid():
            comment = Comment(comment=form.cleaned_data['comment'])
            comment.photo = photos_list
            comment.user = UserProfileInfo.objects.get(user=request.user)
            comment.user.id = UserProfileInfo.objects.get(user=request.user.id)

            comment.see_buttons = False
            if comment.photo.user.user_id == request.user.id:
                comment.see_buttons = True
            comment.save()
            photos_list.save()

        context = {'photos_list': photos_list,
                   'form': CommentPhotoForm(),
                   'profile': current_user, }

        return render(request, 'travel/photo_details.html', context=context)


#def create_photo(request):
#    current_user = request.user
#
#    if request.method == "GET":
#        form = forms.CreatePhotoForm(request.GET)
#        context = {'profile': current_user, }
#        context.update({'form': form})
#
#        return render(request, 'travel/create_photo.html', context=context)
#    elif request.method == "POST":
#        form = forms.CreatePhotoForm(request.POST, request.FILES)
#
#        if form.is_valid():
#           print("VALIDATION SUCCESS")
#          photos_list = Photo.objects.order_by('title')
#         photos_dict = {'photos': photos_list,
#                           'profile': current_user, }
#
#            new_photo = form.save()
#            new_photo.user = UserProfileInfo.objects.get(user=request.user)
#            new_photo.user.id = UserProfileInfo.objects.get(user=request.user.id)
#            new_photo.save()
#           return render(request, 'travel/photos_list.html', context=photos_dict)


class CreatePhotoView(auth_mixins.LoginRequiredMixin, CreateView):
    template_name = 'travel/create_photo.html'
    model = Photo
    form_class = CreatePhotoForm

    def get_success_url(self):
        url = 'http://127.0.0.1:8000/photos/'
        return url

    def form_valid(self, form):
        new_photo = form.save(commit=False)
        new_photo.user = UserProfileInfo.objects.get(user=self.request.user)
        new_photo.user.id = UserProfileInfo.objects.get(user=self.request.user.id)
        new_photo.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        photos_list = Photo.objects.order_by('title')

        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        context['photos'] = photos_list
        return context

# def edit_photo(request, pk):
#     photos_list = get_object_or_404(Photo, pk=pk)
#     current_user = request.user
#
#     if request.method == "GET":
#         form = CreatePhotoForm(instance=photos_list)
#         context = {'profile': current_user, }
#         context.update({'form': form})
#
#         return render(request, 'travel/edit_photo.html', context=context)
#
#
#     elif request.method == "POST":
#
#         form = CreatePhotoForm(request.POST, request.FILES, instance=photos_list)
#         if form.is_valid():
#             photos_list = form.save(commit=False)
#             photos_list.save()
#
#         return redirect(f'http://127.0.0.1:8000/photos/details/{pk}')
#
#     context = {'photos_list': photos_list,
#                'form': CommentPhotoForm()}
#     return render(request, 'travel/photo_details.html', context=context)


class UpdatePhotoView(auth_mixins.LoginRequiredMixin, UpdateView):
    template_name = 'travel/edit_photo.html'
    model = Photo
    form_class = CreatePhotoForm

    def get_success_url(self):
        pk = self.object.id
        url = f'http://127.0.0.1:8000/photos/details/{pk}'

        return url


    def form_valid(self, form):
        new_photo = form.save(commit=False)
        new_photo.user = UserProfileInfo.objects.get(user=self.request.user)
        new_photo.user.id = UserProfileInfo.objects.get(user=self.request.user.id)
        new_photo.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        photos_list = Photo.objects.order_by('title')

        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        context['photos'] = photos_list
        return context


# def delete_photo(request, pk):
#     current_user = request.user
#
#     photos_list = get_object_or_404(Photo, pk=pk)
#
#     if request.method == "GET":
#         form = DeletePhotoForm(instance=photos_list)
#         context = {'profile': current_user, }
#         context.update({'form': form})
#
#         return render(request, 'travel/delete_photo.html', context=context)
#
#
#     elif request.method == "POST":
#
#         photos_list.delete()
#         return redirect('http://127.0.0.1:8000/photos')


class DeletePhotoView(auth_mixins.LoginRequiredMixin, DeleteView):
    model = Photo
    template_name = 'travel/delete_photo.html'
    success_url = 'http://127.0.0.1:8000/photos'

    def get_context_data(self, **kwargs):
        photos_list = Photo.objects.order_by('title')

        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        context['photos'] = photos_list
        return context

def like(request, pk):
    photo = Photo.objects.get(pk=pk)
    like = Like()
    like.photo = photo
    like.user = UserProfileInfo.objects.get(user=request.user)
    like.user.id = UserProfileInfo.objects.get(user=request.user.id)

    like.save()

    likes_of_current_user = 0
    for x in Like.objects.filter(photo=photo):
        if x.user.id == request.user.userprofileinfo.pk:
            likes_of_current_user += 1

    if like.user.id == request.user.userprofileinfo.pk:

        if likes_of_current_user > 1:
            pass
            like.delete()
        else:
            pass

    return redirect(f'http://127.0.0.1:8000/photos/details/{pk}')


def edit_comment(request, pk):
    current_user = request.user

    comments_list = get_object_or_404(Comment, pk=pk)
    pk_of_current_photo = comments_list.photo.pk

    if request.method == "GET":
        form = EditComment(instance=comments_list)
        context = {'profile': current_user, }
        context.update({'form': form})

        return render(request, 'travel/edit_comment.html', context=context)

    elif request.method == "POST":
        form = EditComment(request.POST, instance=comments_list)
        if form.is_valid():
            comments_list = form.save(commit=False)
            comments_list.save()
            return redirect(f'http://127.0.0.1:8000/photos/details/{pk_of_current_photo}')


def delete_comment(request, pk):
    current_user = request.user
    comments_list = get_object_or_404(Comment, pk=pk)
    pk_of_current_photo = comments_list.photo.pk

    if request.method == "GET":
        form = DeleteComment(instance=comments_list)
        context = {'profile': current_user, }
        context.update({'form': form})
        return render(request, 'travel/delete_comment.html', context=context)

    elif request.method == "POST":
        comments_list.delete()
        return redirect(f'http://127.0.0.1:8000/photos/details/{pk_of_current_photo}')


def all_photos_of_user(request, pk):
    current_user = request.user
    photo = get_object_or_404(Photo, pk=pk)
    owner_of_photo_username = photo.user
    owner_of_photo = photo.user.user_id
    filtered_all_photos = []
    all_photos = Photo.objects.all()
    for el in all_photos:
        if el.user.user_id == owner_of_photo:
            filtered_all_photos.append(el)

    context = {'photos_of_user': filtered_all_photos,
               'profile': current_user,
               'owner_of_photo_username': owner_of_photo_username, }

    return render(request, 'travel/photos_of_user.html', context=context)

templates/travel/create_photo.html
{% extends 'common/base.html' %}

{% block content %}

    <div class="container">
        <h1 class="text-center">Add new photo</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">



                <form method="POST" enctype="multipart/form-data" class="furniture-form">

                     {% csrf_token  %}
                    <label for="name">City:</label>

                        {{ form.city }}

                    <label for="name">Country:</label>

                        {{ form.country }}

                    <label for="name">Title:</label>

                        {{ form.title }}

                    <label for="name">Description:</label>

                        {{ form.description }}


                    {{ form.image_url }}

                    <div class="col-lg-6">
                        <button class="btn btn-primary mt-2" type="submit">Create</button>

                    </div>
                </form>




            </div>

            <div class="col-lg-3"></div>
        </div>
    </div>



{% endblock %}

templates/travel/delete_comment.html
{% extends 'common/base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Are you sure you want to delete this comment?</h1>
                <div class="m-auto d-flex justify-content-center">
                    <div class="m-2">
                        <form method="post">

                            {% csrf_token %}


                            <input type="submit" value="Confirm" class="btn btn-danger"/>
                        </form>
                    </div>
                    <div class="m-2">
                        <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>

{% endblock %}

templates/travel/delete_photo.html
{% extends 'common/base.html' %}

{% block content %}




    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Are you sure you want to delete {{ photos_list.title }}?</h1>
                <div class="m-auto d-flex justify-content-center">
                    <div class="m-2">
                        <form method="post">

                            {% csrf_token %}


                            <input type="submit" value="Confirm" class="btn btn-danger"/>
                        </form>
                    </div>
                    <div class="m-2">
                        <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                    </div>
                </div>
                <div> {{ form }}</div>

            </div>

        </div>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>

{% endblock %}

templates/travel/edit_comment.html
{% extends 'common/base.html' %}

{% block content %}

    <div class="container">
        <h1 class="text-center">Edit comment</h1>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" enctype="multipart/form-data" class="furniture-form">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary mt-2" type="submit">Save</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

{% endblock %}

templates/travel/edit_photo.html
{% extends 'common/base.html' %}

{% block content %}

    <div class="container">
        <h1 class="text-center">Edit photo</h1>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" enctype="multipart/form-data" class="furniture-form">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary mt-2" type="submit">Save</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

{% endblock %}

templates/travel/photo_details.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}

    <div style="margin-bottom: 100px">

        <div id="hello" class="container">

            <div class="d-flex">
                <div class="d-inline p-2 w-50">
                    <img src="{{ photos_list.image_url.url }}" class="w-50 rounded mx-auto d-block">
                    <h5 class="w-50 rounded mx-auto d-block">{{ photos_list.city|capfirst }}</h5>
                    <h5 class="w-50 rounded mx-auto d-block">{{ photos_list.country|capfirst }}</h5>
                    <h5>
                        <a href="{% url 'travel:photos_of_user' pk=photos_list.pk %}" id="button_comment"
                           class="w-50 rounded mx-auto d-block">see other photos taken by {{ photos_list.user }}</a>
                    </h5>


                </div>


                <div class="d-inline p-2 w-50">
                    <div class="d-flex justify-content-between">
                        <h5>"{{ photos_list.title|capfirst }}"</h5>

                    </div>
                    <div class="d-flex justify-content-between">
                        <h5> {{ photos_list.description|capfirst }}</h5>

                    </div>
                    {% if photos_list.see_edit_and_delete_button == True %}

                        <a href="{% url 'travel:edit_photo' pk=photos_list.pk %}" class="btn btn-success">Edit</a>
                        <a href="{% url 'travel:delete_photo' pk=photos_list.pk %}" class="btn btn-danger">Delete</a>

                    {% endif %}

                    <P></P>
                    {% if user.is_authenticated %}
                        {% if already_liked == True %}
                            <a href="{% url 'travel:like' pk=photos_list.pk %}"><i class="fa fa-heart"
                                                                                   aria-hidden="true"></i></a>
                        {% else %}
                            <a href="{% url 'travel:like' pk=photos_list.pk %}"><i class="fa fa-heart-o"
                                                                                   aria-hidden="true"></i></a>
                        {% endif %}
                    {% endif %}
                    <p class="mt-2">Likes: {{ photos_list.like_set.count }}</p>


                </div>


            </div>


            <div class="d-block" style="background-color: #d1e3e3; padding:2%">
                {% if photos_list.comment_set.count > 0 %}
                    {% for comment in photos_list.comment_set.all %}
                        <div class="box">

                            <h5><em>{{ comment.user }} : {{ comment }}</em></h5>


                            {% if comment.user.user_id == request.user.id %}
                                <a href="{% url 'travel:edit_comment' pk=comment.pk %}" id="button_comment"
                                   class="btn btn-primary btn-sm">Edit</a>
                                <a href="{% url 'travel:delete_comment' pk=comment.pk %}" id="button_comment"
                                   class="btn btn-primary btn-sm">Delete</a>

                            {% endif %}
                            <hr>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="box">
                        <h3>There are no comments for this photo! </h3>
                    </div>


                {% endif %}
                {% if user.is_authenticated %}

                    <div class="box">
                        <form method="post" enctype="multipart/form-data" class="furniture-form">


                            {% csrf_token %}
                            {{ form }}

                            <P></P>
                            <button class="btn btn-primary mt-2" type="submit">Add comment</button>
                        </form>
                    </div>
                {% endif %}
            </div>

        </div>
    </div>

    <style>

        #button_comment {

            width: 4em;
            height: 1.7em;
            font-size: 10px;
        }


    </style>

{% endblock %}

templates/travel/photos_list.html
{% extends 'common/base.html' %}

{% block content %}

    <div style="margin-bottom: 100px">

        {% if user.is_authenticated %}

            <div id="test" class="container">
                <h5>You can add your most beautiful pictures from all around the world and share it with others</h5>
                <a href="{% url 'travel:create' %}" class="btn btn-primary mt-2">Add new photograph</a></div>

            </div>
        {% else %}
            <h5 class='text-center'>Please sign in to contribute to the collection and add your most beautiful pictures
                from all around the world</h5>


        {% endif %}


    <div class="container-unset">

        <h1 class='text-center'>All photos</h1>
        <ul class="list-photos">
            {% for photo in photos %}

                <div class="row-photo-list">
                    <div class="col-sm">
                        <div class="card" style="width: 18rem;">

                            <img src="{{ photo.image_url.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ photo.city|capfirst }}, {{ photo.country|capfirst }}</h5>
                                <h5 class="card-title">{{ photo.title|capfirst }}</h5>

                                <p class="card-text">{{ photo.description|truncatewords:5|capfirst }}</p>


                                <p class="mt-2">Likes: {{ photo.like_set.count }}</p>

                                <a href="{% url 'travel:photo_details' pk=photo.pk %}" class="btn btn-primary">See
                                    details</a>


                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </ul>
    </div>

    <p></p>



{% endblock %}

templates/travel/photos_of_user.html
{% extends 'common/base.html' %}
{% load static %}
{% block content %}



    <hr>
    {% if True %}
        <h2 class='text-center'>These are {{ owner_of_photo_username }}'s travel photos</h2>




        <div class="container-unset">

            <ul class="list-photos">
                {% for photo in photos_of_user %}

                    <div class="row-photo-list">
                        <div class="col-sm">
                            <div class="card" style="width: 18rem;">

                                <img src="{{ photo.image_url.url }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{ photo.city|capfirst }}, {{ photo.country|capfirst }}</h5>
                                    <h5 class="card-title">{{ photo.title|capfirst }}</h5>

                                    <p class="card-text">{{ photo.description|truncatewords:5|capfirst }}</p>


                                    <p class="mt-2">Likes: {{ photo.like_set.count }}</p>

                                    <a href="{% url 'travel:photo_details' pk=photo.pk %}" class="btn btn-primary">See
                                        details</a>


                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}


            </ul>
        </div>

    {% else %}
        <div class="text-center">
            <h2>You have no photos</h2>
            <a href="{% url 'travel:create' %}" class="btn btn-primary mt-2">Add new photograph</a></div>
        </div>
    {% endif %}

    {% if photos %}
        <div class="text-center">

            <a href="{% url 'accounts:delete_all_my_photos' %}" class="btn btn-primary mt-2"
               id="button_delete_all_photos">Delete all my photos</a></div>
        </div>
    {% endif %}
{% endblock %}