accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import LogoutView

app_name = 'accounts'
urlpatterns = [

    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),
    url(r'^user_logout/$', LogoutView.as_view(), name = 'user_logout'),
    path('profile/<int:pk>/', views.my_profile, name= 'my_profile'),
    path('profile/delete_all_my_photos', views.delete_all_my_photos, name= 'delete_all_my_photos'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from . import views

app_name = 'common'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

travel/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from travel.views import CreatePhotoView, UpdatePhotoView, DeletePhotoView

app_name = 'travel'
urlpatterns = [
    url(r'^create/$', CreatePhotoView.as_view(), name = 'create'),
    url(r'^photos/$', views.all_photosListView.as_view(), name = 'all_photos'),
    path('photos/details/<int:pk>/',views.photo_details, name='photo_details'),
    path('edit/<int:pk>/', UpdatePhotoView.as_view(), name = 'edit_photo'),
    path('delete/<int:pk>/', DeletePhotoView.as_view(), name = 'delete_photo'),
    path('photos/like/<int:pk>/', views.like, name = 'like'),
    path('photos/edit_comment/<int:pk>/',views.edit_comment, name='edit_comment'),
    path('photos/delete_comment/<int:pk>/',views.delete_comment, name='delete_comment'),
    path('photos/details/<int:pk>/photos_of_user/',views.all_photos_of_user, name='photos_of_user'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelover/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('travel.urls')),
    path('', include('accounts.urls')),

]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render


# Create your views here.
from django.views.generic.base import TemplateView


#def index(request):
#    current_user = request.user
#    return render(request, 'common/index.html', context={'profile': current_user, })


class IndexView(TemplateView):
    template_name = 'common/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context

templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Travelover</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css_style.css">

</head>

<body>
{% include 'common/header.html' %}
{% block content %}
{% endblock %}

{% include 'common/footer.html' %}


</body>
</html>

templates/common/footer.html
<div class="card-footer navbar-dark bg-dark footer fixed-bottom text-center">
    <small class="text-light text-center">Travel the world</small>
</div>

templates/common/header.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="{% url 'common:index' %}">Home</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'travel:all_photos' %}">All Photos</a>
            </li>


            <li class="nav-item">
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'travel:all_photos' %}">

                            {% if profile.userprofileinfo.profile_pic %}
                                <img src={{ profile.userprofileinfo.profile_pic.url }} width="30" height="30" alt="">

                            {% else %}
                                <img src="/static/generic_profile_pic.png" width="30" height="30" alt="">


                            {% endif %}


                        </a>
                    </li>
                    <a class="nav-link" href="{% url 'accounts:my_profile' pk=user.pk %}">Welcome, {{ user }}! </a>


                    <li class="nav-item">
                        <a id="welcome_user" class="nav-link" href="{% url 'accounts:user_logout' %}">Sign out</a>
                    </li>


                {% else %}
                    <a class="nav-link" href="{% url 'accounts:user_login' %}">Sign in</a>



                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a>
                    </li>
                {% endif %}

        </ul>
    </div>
</nav>

templates/common/index.html
{% extends 'common/base.html' %}

{% block content %}

    <div style="margin-bottom: 100px">
        <div class="container">
            <div class="jumbotron parent">

                <div class="absolute">
                    <h1 id="index_title" class="display-4">Welcome!</h1>
                    <p id="index_title" class="lead">Share your photos from all around the world.</p>
                    <img style="width: 100%" src="/media/images/collage.jpg" alt="index_image">
                    <hr class="my-4">
                    <div class="inner cover">
                        <h1 class="cover-heading"></h1>
                        <div class="row">
                            <div class="col-lg-6">


                                {% if user.is_authenticated %}
                                    <a href="{% url 'accounts:user_logout' %}" class="btn btn-lg btn-secondary">sign
                                        out</a>

                                {% else %}
                                    <div class="col-lg-6">

                                        <p class="lead">Already have an account? <br>

                                            <a href="{% url 'accounts:user_login' %}" class="btn btn-lg btn-secondary">sign
                                                in</a>
                                        <p class="lead"> Do not have an account? <br>
                                            <a href="{% url 'accounts:register' %}" class="btn btn-lg btn-secondary">sign
                                                up</a>
                                        </p>
                                    </div>
                                {% endif %}

                                </p>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    </body>
    </html>

{% endblock %}